-- MySQL Script generated by MySQL Workbench
-- Tue Apr 17 21:59:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MDA_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MDA_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MDA_DB` DEFAULT CHARACTER SET utf8 ;
USE `MDA_DB` ;

-- -----------------------------------------------------
-- Table `MDA_DB`.`t_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_usuarios` (
  `usu_id` INT NOT NULL,
  `usu_nombres` VARCHAR(100) NOT NULL,
  `usu_apellidos` VARCHAR(100) NOT NULL,
  `usu_password` VARCHAR(100) NOT NULL,
  `usu_email` VARCHAR(200) NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_genero` (
  `gen_id` INT NOT NULL,
  `gen_nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`gen_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_formacion` (
  `form_id` INT NOT NULL,
  `form_nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`form_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_estado_civil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_estado_civil` (
  `est_id` INT NOT NULL,
  `est_nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`est_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_provincia` (
  `prov_id` INT NOT NULL,
  `prov_nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`prov_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_canton`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_canton` (
  `can_id` INT NOT NULL,
  `can_nombre` VARCHAR(100) NULL,
  `can_provincia` INT NOT NULL,
  PRIMARY KEY (`can_id`, `can_provincia`),
  INDEX `fk_c_canton_c_provincia1_idx` (`can_provincia` ASC),
  CONSTRAINT `fk_c_canton_c_provincia1`
    FOREIGN KEY (`can_provincia`)
    REFERENCES `MDA_DB`.`c_provincia` (`prov_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_parroquia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_parroquia` (
  `parr_id` INT NOT NULL,
  `parr_nombre` VARCHAR(100) NULL,
  `parr_canton` INT NOT NULL,
  `parr_provincia` INT NOT NULL,
  PRIMARY KEY (`parr_id`, `parr_canton`, `parr_provincia`),
  INDEX `fk_c_parroquia_c_canton1_idx` (`parr_canton` ASC, `parr_provincia` ASC),
  CONSTRAINT `fk_c_parroquia_c_canton1`
    FOREIGN KEY (`parr_canton` , `parr_provincia`)
    REFERENCES `MDA_DB`.`c_canton` (`can_id` , `can_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_perfil` (
  `perf_cedula` VARCHAR(10) NOT NULL,
  `perf_nombres` VARCHAR(100) NOT NULL,
  `perf_apellidos` VARCHAR(100) NOT NULL,
  `perf_celular` VARCHAR(10) NOT NULL,
  `perf_email` VARCHAR(200) NOT NULL,
  `perf_direccion` VARCHAR(200) NULL,
  `perf_foto` VARCHAR(500) NULL,
  `perf_genero` INT NOT NULL,
  `perf_formacion` INT NOT NULL,
  `perf_estadocivil` INT NOT NULL,
  `perf_parroquia` INT NOT NULL,
  `perf_canton` INT NOT NULL,
  `perf_provincia` INT NOT NULL,
  PRIMARY KEY (`perf_cedula`, `perf_genero`, `perf_formacion`, `perf_estadocivil`, `perf_parroquia`, `perf_canton`, `perf_provincia`),
  INDEX `fk_t_perfil_c_genero1_idx` (`perf_genero` ASC),
  INDEX `fk_t_perfil_c_formacion1_idx` (`perf_formacion` ASC),
  INDEX `fk_t_perfil_c_estado_civil1_idx` (`perf_estadocivil` ASC),
  INDEX `fk_t_perfil_c_parroquia1_idx` (`perf_parroquia` ASC, `perf_canton` ASC, `perf_provincia` ASC),
  CONSTRAINT `fk_t_perfil_c_genero1`
    FOREIGN KEY (`perf_genero`)
    REFERENCES `MDA_DB`.`c_genero` (`gen_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_perfil_c_formacion1`
    FOREIGN KEY (`perf_formacion`)
    REFERENCES `MDA_DB`.`c_formacion` (`form_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_perfil_c_estado_civil1`
    FOREIGN KEY (`perf_estadocivil`)
    REFERENCES `MDA_DB`.`c_estado_civil` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_perfil_c_parroquia1`
    FOREIGN KEY (`perf_parroquia` , `perf_canton` , `perf_provincia`)
    REFERENCES `MDA_DB`.`c_parroquia` (`parr_id` , `parr_canton` , `parr_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_impelementos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_impelementos` (
  `impl_id` INT NOT NULL,
  `impl_nombre` VARCHAR(100) NULL,
  `impl_precio` DECIMAL(10,2) NULL,
  `impl_cantidad` INT NULL,
  PRIMARY KEY (`impl_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_kits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_kits` (
  `kit_id` INT NOT NULL,
  `kit_nombre` VARCHAR(100) NULL,
  `kit_implementos` INT NOT NULL,
  PRIMARY KEY (`kit_id`),
  INDEX `fk_t_kits_t_impelementos_idx` (`kit_implementos` ASC),
  CONSTRAINT `fk_t_kits_t_impelementos`
    FOREIGN KEY (`kit_implementos`)
    REFERENCES `MDA_DB`.`t_impelementos` (`impl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_servicios` (
  `serv_id` INT NOT NULL,
  `serv_nombre` VARCHAR(100) NOT NULL,
  `serv_precio` DECIMAL(10,2) NOT NULL,
  `serv_descripcion` VARCHAR(100) NULL,
  `seerv_kit` INT NOT NULL,
  PRIMARY KEY (`serv_id`),
  INDEX `fk_t_servicios_t_kits1_idx` (`seerv_kit` ASC),
  CONSTRAINT `fk_t_servicios_t_kits1`
    FOREIGN KEY (`seerv_kit`)
    REFERENCES `MDA_DB`.`t_kits` (`kit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_lugares_atencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_lugares_atencion` (
  `aten_id` INT NOT NULL,
  `aten_coorx` DECIMAL(15,6) NULL,
  `aten_coory` DECIMAL(15,6) NULL,
  `aten_nombre` VARCHAR(100) NULL,
  `aten_paciente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`aten_id`, `aten_paciente`),
  INDEX `fk_t_lugares_atencion_t_perfil1_idx` (`aten_paciente` ASC),
  CONSTRAINT `fk_t_lugares_atencion_t_perfil1`
    FOREIGN KEY (`aten_paciente`)
    REFERENCES `MDA_DB`.`t_perfil` (`perf_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_tipo_sangre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_tipo_sangre` (
  `tip_id` INT NOT NULL,
  `tip_nombre` VARCHAR(45) NULL,
  `tip_descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_ficha_medica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_ficha_medica` (
  `ficha_id` INT NOT NULL,
  `fich_medicacion_habitual` VARCHAR(500) NULL,
  `fich_enfermedad_hereditaria` VARCHAR(500) NULL,
  `fich_enfermedad_quirurjica` VARCHAR(500) NULL,
  `fich_recibio_transfucion` VARCHAR(2) NULL,
  `fich_fecha_ultima_mestruacion` DATE NULL,
  `fich_embarazo` VARCHAR(2) NULL,
  `fich_discapacidad` VARCHAR(100) NULL,
  `fich_alergias` VARCHAR(500) NULL,
  `fich_estado_conciencia` VARCHAR(500) NULL,
  `fich_actitud` VARCHAR(500) NULL,
  `fich_estado_nutricional` VARCHAR(45) NULL,
  `fich_hidratacion` VARCHAR(45) NULL,
  `fich_tipo_sangre` INT NOT NULL,
  `fich_paciente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ficha_id`, `fich_tipo_sangre`, `fich_paciente`),
  INDEX `fk_t_ficha_medica_c_tipo_sangre1_idx` (`fich_tipo_sangre` ASC),
  INDEX `fk_t_ficha_medica_t_perfil1_idx` (`fich_paciente` ASC),
  CONSTRAINT `fk_t_ficha_medica_c_tipo_sangre1`
    FOREIGN KEY (`fich_tipo_sangre`)
    REFERENCES `MDA_DB`.`c_tipo_sangre` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_ficha_medica_t_perfil1`
    FOREIGN KEY (`fich_paciente`)
    REFERENCES `MDA_DB`.`t_perfil` (`perf_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_estado_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_estado_consulta` (
  `est_id` INT NOT NULL,
  `est_nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`est_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`c_tipo_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`c_tipo_consulta` (
  `tip_id` INT NOT NULL,
  `tip_nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_peticion_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_peticion_consulta` (
  `pet_id` INT NOT NULL,
  `pet_fecha` DATETIME NULL,
  `pet_paciente` VARCHAR(10) NOT NULL,
  `pet_lugar_atencion` INT NOT NULL,
  `pet_estado` INT NOT NULL,
  `pet_tipo` INT NOT NULL,
  `pet_servicio` INT NOT NULL,
  PRIMARY KEY (`pet_id`, `pet_paciente`, `pet_lugar_atencion`, `pet_estado`, `pet_tipo`, `pet_servicio`),
  INDEX `fk_t_peticion_consulta_t_perfil1_idx` (`pet_paciente` ASC),
  INDEX `fk_t_peticion_consulta_t_lugares_atencion1_idx` (`pet_lugar_atencion` ASC),
  INDEX `fk_t_peticion_consulta_c_estado_consulta1_idx` (`pet_estado` ASC),
  INDEX `fk_t_peticion_consulta_c_tipo_consulta1_idx` (`pet_tipo` ASC),
  INDEX `fk_t_peticion_consulta_t_servicios1_idx` (`pet_servicio` ASC),
  CONSTRAINT `fk_t_peticion_consulta_t_perfil1`
    FOREIGN KEY (`pet_paciente`)
    REFERENCES `MDA_DB`.`t_perfil` (`perf_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_peticion_consulta_t_lugares_atencion1`
    FOREIGN KEY (`pet_lugar_atencion`)
    REFERENCES `MDA_DB`.`t_lugares_atencion` (`aten_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_peticion_consulta_c_estado_consulta1`
    FOREIGN KEY (`pet_estado`)
    REFERENCES `MDA_DB`.`c_estado_consulta` (`est_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_peticion_consulta_c_tipo_consulta1`
    FOREIGN KEY (`pet_tipo`)
    REFERENCES `MDA_DB`.`c_tipo_consulta` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_peticion_consulta_t_servicios1`
    FOREIGN KEY (`pet_servicio`)
    REFERENCES `MDA_DB`.`t_servicios` (`serv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDA_DB`.`t_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDA_DB`.`t_consulta` (
  `cons_id` INT NOT NULL,
  `cons_fecha` TIMESTAMP(0) NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `cons_peticion` INT NOT NULL,
  `cons_paciente` VARCHAR(10) NOT NULL,
  `cons_enfermera` VARCHAR(10) NOT NULL,
  `cons_medico` VARCHAR(100) NULL,
  `cons_foto_receta` VARCHAR(500) NULL,
  `cons_reaccion_adversa` VARCHAR(100) NULL,
  `cons_informe_enfermeria` VARCHAR(100) NULL,
  `cons_observaciones` VARCHAR(300) NULL,
  PRIMARY KEY (`cons_id`, `cons_peticion`, `cons_paciente`, `cons_enfermera`),
  INDEX `fk_t_consulta_t_peticion_consulta1_idx` (`cons_peticion` ASC),
  INDEX `fk_t_consulta_t_perfil1_idx` (`cons_paciente` ASC),
  INDEX `fk_t_consulta_t_perfil2_idx` (`cons_enfermera` ASC),
  CONSTRAINT `fk_t_consulta_t_peticion_consulta1`
    FOREIGN KEY (`cons_peticion`)
    REFERENCES `MDA_DB`.`t_peticion_consulta` (`pet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_consulta_t_perfil1`
    FOREIGN KEY (`cons_paciente`)
    REFERENCES `MDA_DB`.`t_perfil` (`perf_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_consulta_t_perfil2`
    FOREIGN KEY (`cons_enfermera`)
    REFERENCES `MDA_DB`.`t_perfil` (`perf_cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
